"""add description3

Revision ID: f89a0b38e90d
Revises: b8a4933a4a58
Create Date: 2023-06-23 16:18:02.528464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89a0b38e90d'
down_revision = 'b8a4933a4a58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
